// Code generated by "stringer -type=Action"; DO NOT EDIT.

package actions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Takeoff-0]
	_ = x[Land-1]
	_ = x[Up-2]
	_ = x[Down-3]
	_ = x[Left-4]
	_ = x[Right-5]
	_ = x[Forward-6]
	_ = x[Backward-7]
	_ = x[RotateRight-8]
	_ = x[RotateLeft-9]
	_ = x[Hover-10]
	_ = x[FrontFlip-11]
	_ = x[Backflip-12]
	_ = x[LeftFlip-13]
	_ = x[RightFlip-14]
}

const _Action_name = "TakeoffLandUpDownLeftRightForwardBackwardRotateRightRotateLeftHoverFrontFlipBackflipLeftFlipRightFlip"

var _Action_index = [...]uint8{0, 7, 11, 13, 17, 21, 26, 33, 41, 52, 62, 67, 76, 84, 92, 101}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
